package com.kakao.actionbase.v2.engine.storage.slatedb

import java.nio.file.Files
import java.nio.file.StandardCopyOption

// Workaround for io.slatedb:slatedb-uniffi:0.12.x. The Java bindings are
// generated by IronCoreLabs/uniffi-bindgen-java, whose FFM loader resolves
// the library via `System.loadLibrary` / `System.load` and intentionally does
// not extract bundled natives from the classpath — consumers pass an absolute
// path via the `uniffi.component.<ns>.libraryOverride` system property
// (see IronCoreLabs/uniffi-bindgen-java#58 and #59). The slatedb jar happens
// to ship the libraries as JNA-style resources, but no loader uses them.
//
// This helper materializes the OS/arch-specific resource to a temp file and
// sets that property. Delete this file if upstream ever ships a
// classpath-aware loader.
private const val LIBRARY_OVERRIDE_PROPERTY = "uniffi.component.slatedb.libraryOverride"

internal fun extractSlateDbNativeLibrary() {
    // Skip if the user already pinned the library path (e.g. for local dev
    // against a built-from-source dylib).
    if (System.getProperty(LIBRARY_OVERRIDE_PROPERTY) != null) return

    val osName = System.getProperty("os.name").lowercase()
    val osArch = System.getProperty("os.arch").lowercase()
    val (osDir, libFileName) =
        when {
            osName.contains("mac") || osName.contains("darwin") -> "darwin" to "libslatedb_uniffi.dylib"
            osName.contains("linux") -> "linux" to "libslatedb_uniffi.so"
            osName.contains("windows") -> "win32" to "slatedb_uniffi.dll"
            else -> error("Unsupported OS for SlateDB UniFFI native library: $osName")
        }
    val archDir =
        when {
            osArch.contains("aarch64") || osArch.contains("arm64") -> "aarch64"
            osArch.contains("amd64") || osArch.contains("x86_64") || osArch == "x86-64" -> "x86-64"
            else -> error("Unsupported architecture for SlateDB UniFFI native library: $osArch")
        }
    val resourcePath = "$osDir-$archDir/$libFileName"
    val input =
        Thread.currentThread().contextClassLoader.getResourceAsStream(resourcePath)
            ?: error("SlateDB UniFFI native library not bundled at classpath resource $resourcePath")

    val suffix = "." + libFileName.substringAfterLast('.')
    val tempFile = Files.createTempFile("slatedb_uniffi", suffix)
    tempFile.toFile().deleteOnExit()
    input.use { Files.copy(it, tempFile, StandardCopyOption.REPLACE_EXISTING) }
    System.setProperty(LIBRARY_OVERRIDE_PROPERTY, tempFile.toAbsolutePath().toString())
}
